# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('jobspec', '0001_initial'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10, null=True, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('jobsepc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobspec.JobSpec')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteCardReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.IntegerField()),
                ('production_qty', models.IntegerField(default=0)),
                ('rejection_qty', models.IntegerField(default=0)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Process')),
                ('routecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routecard.RouteCard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
