# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-04 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecardreport',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routecardreport',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
