# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_monthly_available_hours'),
        ('process', '0004_process_machine'),
        ('routecard', '0002_auto_20160904_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.Machine')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Process')),
                ('routecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routecard.RouteCard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
