# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0004_plan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routecard',
            name='jobsepc',
        ),
    ]
