# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0006_routecard_jobspec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routecardreport',
            name='process',
        ),
        migrations.RemoveField(
            model_name='routecardreport',
            name='routecard',
        ),
    ]
