# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-09 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0008_auto_20160907_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Machine'),
        ),
    ]
