# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-19 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0009_auto_20160909_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='time',
        ),
        migrations.AlterField(
            model_name='routecardreport',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='routecard.Plan'),
        ),
    ]
