# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-19 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0010_auto_20160919_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeQuanta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='routecard.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
