# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-29 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0011_timequanta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routecard',
            name='number',
        ),
    ]
