# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0012_remove_routecard_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecard',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
