# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0014_auto_20160930_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routecard',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
