# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-06 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0015_auto_20160930_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecard',
            name='devivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='routecard',
            name='po.no',
            field=models.CharField(default=datetime.datetime(2016, 10, 6, 10, 42, 27, 23954, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
