# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-06 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0016_auto_20161006_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routecard',
            old_name='devivery_date',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='routecard',
            old_name='po.no',
            new_name='po_no',
        ),
    ]
