# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0017_auto_20161006_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecard',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
