# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-17 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0018_routecard_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routecard',
            name='start_time',
        ),
    ]
