# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0019_remove_routecard_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='planned_on',
            field=models.DateTimeField(null=True),
        ),
    ]
