# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-18 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0020_plan_planned_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routecardreport',
            name='shift',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
