# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routecard', '0021_auto_20161018_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
