# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-04 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='monthly_available_hours',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
