# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_remove_machine_monthly_available_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
