# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_process_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='jobsepc',
        ),
    ]
