# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20160907_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='estimated_setting_time',
            field=models.DurationField(null=True),
        ),
    ]
