# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-07 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_process_estimated_setting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='jobsepc',
        ),
    ]
