# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-07 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_process_jobsepc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='jobsepc',
            new_name='jobspec',
        ),
    ]
