# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-29 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_auto_20160907_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
