# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_process_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
