# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_auto_20160930_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processname',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
