# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-29 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobspec', '0002_auto_20160926_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobspec',
            name='number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Parts No'),
        ),
    ]
